---
  - name: "This Play is to Launch EC2 Instances with multiple sequrity groups and Tags"
    gather_facts: false
    hosts:  localhost
    connection: local
    tasks:
      - name: This task is to create EC2
        amazon.aws.ec2_instance:
          instance_type: t2.small
          image_id:  ami-08d01bf321ad0777e
          count:  1
          key_name: tf-testing
          region: us-east-1
          wait: yes
          security_group: sg-00054d902c8e915a0
          vpc_subnet_id:  subnet-04c8a1cce0a80f526
          iam_instance_profile: tf-role-testing 
          tags:
            DataClassification: restricted
            Environment: poc
            AppName:  as-testing-client-1
            InfraOwner: sre-cloud-reliability@tavisca.com
            BusinessUnit: travel.app
            Backup: 'no'
            Product: poap
            Name: as-testing-client-1  
