---
  - name: "install_and_configure_tomcat"
    hosts:  all
    gather_facts: false
    become: yes
    vars:
      req_java: java-1.8.0-openjdk
      req_tomcat_ver: 9.0.83
      tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
      tomcat_port:  8091
    tasks:
      - name: updated repo and package
        yum: 
          name: '*'
          state:  latest

      - name: Install Java
        yum: 
          name: java-1.8.0-openjdk
          state:  present
      
      - name: change current Java version
        alternatives:
          name: java
          link: /usr/bin/java
          path: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-1.amzn2.0.2.x86_64/jre/bin/java"

      - name: Downloading required Software
        get_url:
          url:  "{{tomcat_url}}"
          dest: /tmp
      
      - name: Extracting downloaded tomcat
        unarchive:
          src: "/tmp/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
          dest: /tmp
          remote_src: yes

      - name: "renaming tomcat home"
        command:  mv "/tmp/apache-tomcat-{{req_tomcat_ver}}" "/usr/local/latest//apache-tomcat-{{req_tomcat_ver}}"

      - name: "Replacing Default portiwth required port"
        template: 
          src:  ./server.xml.j2
          dest: /usr/local/latest/apache-tomcat-{{req_tomcat_ver}}/conf/server.xml

      - name: "Start tomcat"
        shell:  /usr/local/latest/apache-tomcat-{{req_tomcat_ver}}/bin/startup.sh &

      - name: "Reading SSM parameter value"
        debug:
          msg:
            - " value of parameter PrimaryInstanceName is : {{lookup('aws_ssm','PrimaryInstanceName')}}"

      
