---
  - name: "Play for Reading SSM parameter value"
    hosts:  all
    gather_facts: false
    become: yes
    tasks:      
      
      - name: Check binaries and versions
        shell: |
          echo $PATH
          export PATH=$PATH:$HOME/.local/bin
          echo $PATH
          which python3
          python3 --version
          which pip3
          pip3 --version
          which ansible
          ansible --version
          pip3 list | grep -e ansible -e boto
          python3 -c 'import botocore'
          python3 -c 'import boto3'

      # - name: "install boto3 for ssm parameter lookup"
      #   ansible.builtin.pip:
      #     name: boto3
      #     executable: pip3.7
      - name: Ensure boto3, botocore and ansible modules are installed
        pip:
          name: 
            - boto3
            - botocore
          executable: /usr/bin/pip3

      - name: "Reading SSM parameter value"
        debug:
          msg:
            - " value of parameter PrimaryInstanceName is : {{lookup('amazon.aws.aws_ssm','PrimaryInstanceName',region='us-east-1')}}"